export interface CheatSheetItem {
  category: string;
  title: string;
  description: string;
  commandsOrSyntax: { label: string; code: string }[];
  keyTips: string[];
}

export const CHEATSHEET_DATA: CheatSheetItem[] = [
  {
    category: 'Common Ports & Protocols',
    title: 'Essential Network Security Port Numbers',
    description: 'Every network security interview requires instant recall of these well-known Layer 4 transport ports and protocols.',
    commandsOrSyntax: [
      { label: 'HTTP / HTTPS', code: 'TCP 80 (HTTP plaintext), TCP 443 (HTTPS TLS encrypted)' },
      { label: 'DNS (Domain Name System)', code: 'UDP 53 (Standard queries), TCP 53 (Zone transfers / >512B replies)' },
      { label: 'SSH / Telnet', code: 'TCP 22 (Secure Shell), TCP 23 (Telnet plaintext - Insecure)' },
      { label: 'Databases', code: 'TCP 3306 (MySQL), TCP 5432 (PostgreSQL), TCP 1433 (MS SQL), TCP 1521 (Oracle)' },
      { label: 'IPsec / VPN', code: 'UDP 500 (IKE), UDP 4500 (NAT-T), Protocol 50 (ESP), Protocol 51 (AH)' },
      { label: 'Remote Access / Windows', code: 'TCP 3389 (RDP), TCP 445 (SMB), TCP 88 (Kerberos), TCP 389/636 (LDAP/LDAPS)' }
    ],
    keyTips: [
      'DNS uses UDP 53 for normal queries for speed, but falls back to TCP 53 if responses exceed 512 bytes (or DNSSEC) and for zone transfers (AXFR).',
      'Always differentiate IP protocol numbers (TCP=6, UDP=17, ICMP=1, ESP=50) from port numbers.'
    ]
  },
  {
    category: 'Firewall CLI Commands',
    title: 'Linux iptables & nftables Quick Reference',
    description: 'Practical syntax for packet filtering, NAT, and connection tracking.',
    commandsOrSyntax: [
      { label: 'List all rules with line numbers', code: 'iptables -L -n -v --line-numbers' },
      { label: 'Allow established return traffic', code: 'iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT' },
      { label: 'Block an abusive IP immediately', code: 'iptables -I INPUT 1 -s 198.51.100.25 -j DROP' },
      { label: 'Configure NAT Port Forwarding (DNAT)', code: 'iptables -t nat -A PREROUTING -p tcp --dport 443 -j DNAT --to-destination 10.0.1.50:443' },
      { label: 'Inspect live state table', code: 'conntrack -L | grep ESTABLISHED' }
    ],
    keyTips: [
      '-I inserts a rule at a specific line number (e.g. line 1 for high priority). -A appends to the very end.',
      'Remember the 3 default filter chains: INPUT (to local host), FORWARD (routed through host), OUTPUT (generated by host).'
    ]
  },
  {
    category: 'Wireshark & Packet Capture',
    title: 'Wireshark Display Filters for Security Triage',
    description: 'Speed filter expressions for diagnosing firewall drops and TCP handshake anomalies.',
    commandsOrSyntax: [
      { label: 'Find TCP SYN Packets (Connection Initiation)', code: 'tcp.flags.syn == 1 && tcp.flags.ack == 0' },
      { label: 'Find TCP Resets (Firewall Rejections)', code: 'tcp.flags.reset == 1' },
      { label: 'Filter Specific Host & Port', code: 'ip.addr == 192.168.1.50 && tcp.port == 443' },
      { label: 'Find TLS Handshake Failures / ClientHello', code: 'tls.handshake.type == 1' },
      { label: 'Detect Potential Port Scans', code: 'tcp.flags.syn == 1 && tcp.flags.ack == 0 && !tcp.analysis.retransmission' }
    ],
    keyTips: [
      'Wireshark display filters (`ip.addr == ...`) filter already-captured packets, whereas BPF capture filters (`host ...`) filter at the network driver before capture.',
      'A stream of SYN packets with no response indicates a DROP (timeout), whereas an immediate RST indicates a REJECT.'
    ]
  },
  {
    category: 'Interview Frameworks',
    title: 'The "5-Tuple" and "OSI Model" Cheat Matrix',
    description: 'How to structure any network troubleshooting or architecture answer in an interview.',
    commandsOrSyntax: [
      { label: 'The 5-Tuple', code: '1. Source IP\n2. Destination IP\n3. Source Port\n4. Destination Port\n5. Layer 4 Protocol (TCP/UDP/ICMP)' },
      { label: 'OSI Security Stack', code: 'L7 App: WAF, App-ID, HTTP/TLS\nL4 Transport: TCP/UDP ports, Stateful tracking\nL3 Network: IP routing, Subnets, ICMP, IPsec\nL2 Data Link: MAC addresses, VLAN tags, ARP\nL1 Physical: Cables, Fiber, NIC links' }
    ],
    keyTips: [
      'Start your technical explanations at Layer 3/4 before moving to Layer 7.',
      'Always refer to the 5-tuple when asked how firewalls or NAT identify and track streams.'
    ]
  }
];
